script:
 - "travis.rb"

language: sass
before_install:
 - gem install sass

notifications:
  irc:
    channels:
      - "irc.esper.net#kurisu"
    template:
      - "%{repository} (%{commit}) {branch}"
      - "%{author} %{message}"
    use_notice: true
    skip_join: true